# Generated by Django 2.1.3 on 2018-11-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bucketlist',
            table='techno_bucketlist',
        ),
    ]
